### ISSUE TITLE
PHP Debricated PHP Deprecated:  Non-static method Ptondereau\PackMe\Commands\CreateCommand::handle() 

### ISSUE THREAD

**Issue by okaufmann** [ptondereau/laravel-packme#13]
First, thanks for this greate package!

After the last update one can't use packme anymore. When run on windows or homestead I got this message:

```
PHP Deprecated:  Non-static method Ptondereau\PackMe\Commands\CreateCommand::handle() should not be called statically in {Roaming}\vendor\mnapoli\silly\src\Application.php on line 207
```

```
Deprecated: Non-static method Ptondereau\PackMe\Commands\CreateCommand::handle() should not be called statically in {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php on line 207
PHP Fatal error:  Uncaught TypeError: ReflectionFunction::__construct() expects parameter 1 to be string, array given in {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php:209
Stack trace:
#0 {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php(209): ReflectionFunction->__construct(Array)
#1 {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php(97): Silly\Application->defaultsViaReflection(Array)
#2 {Roaming}\Composer\vendor\ptondereau\laravel-packme\src\packme.php(39): Silly\Application->command('create [dir]', Array)
#3 {main}
  thrown in {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php on line 209

Fatal error: Uncaught TypeError: ReflectionFunction::__construct() expects parameter 1 to be string, array given in {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php:209
Stack trace:
#0 {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php(209): ReflectionFunction->__construct(Array)
#1 {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php(97): Silly\Application->defaultsViaReflection(Array)
#2 {Roaming}\Composer\vendor\ptondereau\laravel-packme\src\packme.php(39): Silly\Application->command('create [dir]', Array)
#3 {main}
  thrown in {Roaming}\Composer\vendor\mnapoli\silly\src\Application.php on line 209

```

**Comment by ptondereau** [comment]
Hello @okaufmann 

Thanks for reporting this issue. Indeed,  Silly CLI have updated its own API. I've just made an PR #14 to fix it. Then I will draft a new release (2.0.8)

**Comment by ptondereau** [comment]
@okaufmann merged and released ;)

**Comment by okaufmann** [comment]
Wow! That was fast.

It works again!

**Comment by okaufmann** [comment]
And of course thank you well ;)
